[2024-09-23 14:50:32,582] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.6:5000 (Press CTRL+C to quit) - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:50:32,584] INFO _log() L224   * Restarting with stat - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:50:39,823] ERROR predict() L102  Erro ao adicionar paciente: 'dict' object has no attribute 'age' - call_trace=C:\Napolis\Estudos\Pós - Engenharia de Software\4° Sprint - Machine Learning\MVP\api\app.py L102 
[2024-09-23 14:50:39,825] INFO _log() L224  127.0.0.1 - - [23/Sep/2024 14:50:39] "[35m[1mPOST /paciente HTTP/1.1[0m" 500 - - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:53:21,697] INFO _log() L224   * Detected change in 'C:\\Napolis\\Estudos\\Pós - Engenharia de Software\\4° Sprint - Machine Learning\\MVP\\api\\app.py', reloading - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:53:21,897] INFO _log() L224   * Restarting with stat - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:53:24,591] INFO _log() L224  127.0.0.1 - - [23/Sep/2024 14:53:24] "POST /paciente HTTP/1.1" 200 - - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:55:59,989] INFO _log() L224   * Detected change in 'C:\\Napolis\\Estudos\\Pós - Engenharia de Software\\4° Sprint - Machine Learning\\MVP\\api\\model\\preprocessador.py', reloading - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:56:00,246] INFO _log() L224   * Restarting with stat - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:56:02,054] INFO _log() L224   * Detected change in 'C:\\Napolis\\Estudos\\Pós - Engenharia de Software\\4° Sprint - Machine Learning\\MVP\\api\\app.py', reloading - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:56:02,269] INFO _log() L224   * Restarting with stat - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:56:07,503] WARNING predict() L93   Erro ao adicionar paciente 'Zé Ruela', Paciente já existente na base - call_trace=C:\Napolis\Estudos\Pós - Engenharia de Software\4° Sprint - Machine Learning\MVP\api\app.py L93  
[2024-09-23 14:56:07,505] INFO _log() L224  127.0.0.1 - - [23/Sep/2024 14:56:07] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:56:11,682] INFO _log() L224  127.0.0.1 - - [23/Sep/2024 14:56:11] "POST /paciente HTTP/1.1" 200 - - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:57:02,041] INFO _log() L224   * Detected change in 'C:\\Napolis\\Estudos\\Pós - Engenharia de Software\\4° Sprint - Machine Learning\\MVP\\api\\model\\preprocessador.py', reloading - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 14:57:02,248] INFO _log() L224   * Restarting with stat - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 15:04:16,414] INFO _log() L224   * Detected change in 'C:\\Napolis\\Estudos\\Pós - Engenharia de Software\\4° Sprint - Machine Learning\\MVP\\api\\app.py', reloading - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-23 15:04:16,677] INFO _log() L224   * Restarting with stat - call_trace=C:\Program Files\Python311\Lib\site-packages\werkzeug\_internal.py L224 
